config/routes.rb
Rails.application.routes.draw do
  scope '/plantfadb' do
    resources :dbxrefs
    resources :fatty_acids
    resources :results do
      get 'plant_yield', on: :collection
    end
    resources :measures do
      get :autocomplete_measure_name, :on => :collection
    end
    resources :plants do
      get :autocomplete_plant_name, :on => :collection
    end
    resources :pubs do
      collection do
        post 'condense_doi'
        post 'condense_wos'
      end
    end
    resources :plants_pubs
    resources :drafts
    devise_for :users
    resources :users
    resources :pages
    resources :tree, only: :index do
      get 'data', on: :collection
    end
    resources :datasets
    resources :tree_nodes do
      get :manage, on: :collection
      collection do
        post :sort
      end
    end

    root 'home#index'
    get 'stats' => 'stats#index'
    get 'history' => 'history#index'
    get 'species' => 'species#index', as: 'species'
    get ':genus/:species' => 'species#show', as: 'species_page'
    
    get 'bulk_uploads' => 'bulk_uploads#index'
    post 'check_file' => 'bulk_uploads#check_file'
    post 'process_file' => 'bulk_uploads#process_file'
    

  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  skip_authorization_check
  
  def index
    oil_content = Parameter.where("upper(delta_notation)='OIL CONTENT'").first
    @species = Plant.all
    if ActiveRecord::Base.connection.adapter_name.downcase =~ /.*sqlite.*/
      @species = @species.order(sort_column + ' ' + sort_direction+", plants.genus asc, plants.species asc")
    else
      @species = @species.order(sort_column + ' ' + sort_direction+" nulls last, plants.genus asc, plants.species asc")
    end
                       
    @species = @species.joins(plants_pubs: [:pub, datasets: [results: :measure]])
                       .joins("left outer join results oil_res on oil_res.dataset_id = datasets.id and oil_res.measure_id = #{oil_content.id}")
                       .where("results.unit in ('GLC-Area-%','weight-%')")
                       .where("measures.type in ('FattyAcid','Parameter')")
                       .where("plants.published_at IS NOT NULL")
                       .where("pubs.published_at IS NOT NULL")
                       .where("results.published_at IS NOT NULL")
                      
      
    if(params[:query])
      q = UnicodeUtils.upcase(params[:query])
      @species = @species.where('
        upper(plants.sofa_name) LIKE ?
        OR upper(plants.note) LIKE ?
        OR upper(plants.sofa_family) LIKE ?
        OR upper(plants.order_name) LIKE ?
        OR upper(plants.family) LIKE ?
        OR upper(plants.genus) LIKE ?
        OR upper(plants.species) LIKE ?
        OR upper(plants.tnrs_family) LIKE ?
        OR upper(plants.tnrs_name) LIKE ?
        OR upper(plants.common_name) LIKE ?
        OR upper(plants.variety) LIKE ?
        OR upper(plants.genus || \' \' || plants.species) LIKE ?',
        "%#{q}%","%#{q}%","%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%","%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%"
      )
    end
    @species = @species.group([:genus, :species]).page(params[:page])
                        .select("plants.genus, plants.species,
                                avg(oil_res.value) avg_oil_content,
                                count(distinct(pubs.id)) pub_count,
                                count(distinct(results.id)) result_count,
                                count(distinct(plants.id)) plant_count"
                               )
    
    respond_to do |format|
      # Base html query
      format.html{}
    end
  end
  
  def show
    @species = Species.new(params[:genus],params[:species])
    if @species.valid?
      @fatty_acid_data = {}
      @parameter_data = {}
      @results = @species.results.includes(:measure).order("measures.delta_notation").where(unit: ['GLC-Area-%','weight-%'])
      @results.where("measures.type = 'FattyAcid'").each do |result|
        next unless result.unit == 'GLC-Area-%' || result.unit == 'weight-%'
        @fatty_acid_data[result.measure_id]||={object:result.measure,values:[]}
        @fatty_acid_data[result.measure_id][:values]<<result.value.to_f.round(2)
      end
      @fatty_acid_data = @fatty_acid_data.map{|k,v| v}
      @results.where("measures.type = 'Parameter'").each do |result|
        @parameter_data["#{result.measure.delta_notation}#{result.unit ? ' - '+result.unit : ''}"]||=[]
        #@parameter_data["#{result.measure.delta_notation}#{result.unit ? ' - '+result.unit : ''}"]<<result.value.round(2)
        @parameter_data["#{result.measure.delta_notation}#{result.unit ? ' - '+result.unit : ''}"] << {id: result.id, value: result.value.round(2)}
      end
    else
      redirect_to root_path
    end
  end
  
  private
  def sort_column
    col = ['genus','species','plant_count','avg_oil_content','pub_count', 'result_count'].find{|c| c==params[:sort]}
    col || 'plants.genus, plants.species'
  end
end

app/views/species/index.html.erb
<% content_for :title do -%>
 PhyloFAdb: Plant Species
<% end -%>

<% content_for :description do -%>
  Fatty acid analysis for more than 6000 plant species including fatty acid composition, oil content, links to publications and individual data sets.
<% end -%>

<% content_for :top_bar do %>
	<h1 class="pagetitle">Species</h1>
<% end %>

<% content_for :item_bar do %>
    <%#= link_to 'Download', params.merge(format: 'csv'), class: 'btn btn-primary'%>
<% end %>
	
<div class='row'>
	<div class='col-xs-12 col-sm-7 col-md-8 pull-left'>
		<ul class="pagination">
			<%= paginate @species %>
		</ul>
	</div>
	<div class='col-xs-12 col-sm-5 col-md-4 search'>
    <%= form_tag nil, method: :get do %>
		<% params.except(:commit,:action,:controller,:utf8,:query).each do |parameter, val| %>
			<%= hidden_field_tag parameter, val %>
		<% end %>
      <div class='form-inline pull-left-sm pull-right-md'>
				<div class='form-group'>
          <a href='<%= Page.path('help') %>'class='glyphicon glyphicon-question-sign' data-toggle='tooltip' data-html='true' title="
            Search includes Order, family, Genus, species, common names and names from the SOFA database.<br/><br/>
            
            Click for more details.
          "></a>
			    <label for="query">Search:</label>
					<%= text_field_tag :query, params[:query], class: 'form-control' %>
					<%= submit_tag "Go", class: "btn btn-info"%>
				</div>
			</div>
    <% end %>
	</div>
</div>

<div class='panel table-responsive'>
	
	<div class="panel-heading clearfix">
		<div class='pull-right'><%= page_entries_info @species %></div>
	</div>
	
  <table class='table table-striped'>
    <thead>
      <tr>
        <th><%= sortable('genus','Genus') %></th>
        <th><%= sortable('species','Species') %></th>
				<th>Common Name</th>
				<th>Family</th>
				<th>Order</th>
				<th><%= sortable('avg_oil_content', 'Oil Content') %></th>
        <th><%= sortable('pub_count','Publications') %></th>
        <th><%= sortable('result_count','Data points') %></th>
        <th><%= sortable('plant_count','Plants') %></th>
      </tr>
    </thead>

    <tbody>
      <% @species.each do |sp| %>
        <% s = Species.new(sp.genus, sp.species) %>
        <tr>
					<td><%= link_to s.genus, species_page_path(genus: s.genus, species: s.species) %></td>
					<td><%= link_to s.species, species_page_path(genus: s.genus, species: s.species) %></td>
					<td style='max-width:150px;overflow:auto;white-space:nowrap'><%= s.common_name %></td>
					<td style='max-width:150px;overflow:auto;white-space:nowrap'><%= s.family %></td>
					<td style='max-width:150px;overflow:auto;white-space:nowrap'><%= s.order_name %></td>
					<td><%= sp.avg_oil_content.try(:round,1) %></td>
          <td><%= link_to sp.pub_count, pubs_path(genus: s.genus, species: s.species) if sp.pub_count %></td>
          <td><%= link_to sp.result_count, results_path(genus: s.genus, species: s.species) if sp.result_count %></td>
          <td><%= link_to s.plants.length, plants_path(genus: s.genus, species: s.species, target: '_blank') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class='row'>
	<div class='col-xs-12 col-sm-7 col-md-8'>
		<ul class="pagination pull-left">
			<%= paginate @species %>
		</ul>
	</div>
</div>

app/views/species/show.html.erb
<% content_for :title do -%>
 PhyloFAdb: <%= @species.name_and_common_name %>
<% end -%>

<% content_for :description do -%>
 Plant fatty acid compositions and phylogenetics. <%= @species.name_and_common_name %>
<% end -%>

<h1 class='pagetitle'>
  <%= @species.name %>
  <small style='white-space:nowrap'><%= @species.common_name %></small>
</h1>

<div class='container'>
	<div class='col-md-4'>
		<div class='well' style='overflow:scroll'>
			<legend>Classification</legend>
			<div style='min-height:300px'>
				<p>
				  <strong>Order:</strong>
				  <%= @species.order_name %>
				</p>
				<p>
				  <strong>Family:</strong>
				  <%= @species.family %>
				</p>
				<p>
				  <strong>Genus:</strong>
				  <%= @species.genus %>
				</p>
				<p>
				  <strong>Species:</strong>
				  <%= @species.species %>
				</p>
				<% unless @species.common_name.blank? %>
					<p>
					  <strong>Common Name:</strong>
					  <%= @species.common_name %>
					</p>
				<% end %>
			</div>
		</div>

	</div>
	<div class='col-md-8'>
		<div class='well' style='overflow:scroll'>
			<legend>Data</legend>
			<small>
				Mouse over individual data points for link to data and publication.<br/>
				The graphs are built from data from all publications in the database with this species name.
				In some cases this results in data from more than one variety included in the graph.
				In other cases the same species may have multiple graphs because of differences in names recorded for the plant.
				
			</small><br/><br/>
			<span> 
				<%= link_to "Show #{pluralize @species.plants.count,"Plant Varieties"}", "#0", onclick: '$("#plant_table").slideToggle();return false;' %>
			</span> |
			<span>
				<%= link_to "View #{pluralize @species.results.published.viewable.count, "Data Point"}", results_path(genus: @species.genus, species: @species.species) %>
			</span>
      
      <div id='plant_table' style='display:none'>
  			<legend><h5>Plant Varieties</h5></legend>				
    		<table class="table">
    		  <thead>
            <th>Name</th>
            <th>Variety</th>
    		    <th>Tissue</th>
            <th></th>
            <th>Data</th>
    		  </thead>
    		  <tbody>
    		    <% @species.plants.order("created_at asc").each do |plant| %>
    		    <tr>
              <td><%= link_to plant.display_name, plant_path(plant) %></td>
    		      <td><%= link_to plant.variety, plant_path(plant) if plant.variety%></td>
    		      <td><%= plant.tissue %></td>
              <td><%= plant.sofa_name %></td>
    					<td>
                <%= plant.results.count %>
              </td>
    		    </tr>
    		    <% end %>
    		  </tbody>
    		</table>
      </div>
        
			<% unless @fatty_acid_data.empty? %>
				<legend><h5>Fatty Acid Data</h5></legend>
					<div id='fa_plant_data_viz_0' style='min-width:700px;height:350px;position:relative'>
						
					</div>
					<div style='margin-left:5em;margin-right:3em'>
						<small><i>
						In cases where some publications report, for example 18:1, and other publications report 18:1-delta-9c (oleic),
						data are presented separately on the x-axis.
						</i></small>
					</div>
			<% end %>
			<% unless @parameter_data.empty? %>
			<legend><h5>Parameters</h5></legend>
			<p>Each bar represents data from a different publication or analysis within a publication</p>
				<% @parameter_data.each_with_index do |(key, subdata),index| %>
					<div id='p_plant_data_viz_<%= index %>' style='min-width:700px;height:350px'></div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

<hr/>

<style>
.scatter {
  font: 10px sans-serif;
}

.scatter {
  font: 10px sans-serif;
}

.scatter line,

.scatter .point {
  fill: steelblue;
  stroke: none;
	opacity: .65;
	pointer-events: none;
}

.scatter rect {
/*	fill: #e4e4e7;*/
	fill: none;
	stroke: none;
	cursor: pointer;
	pointer-events:all;
}
.axis {
  font: 12px sans-serif;
}
 
.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}
 
.x.axis path { 
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}
</style>

<script>
function drawBoxPlot(data,el,unit){
	var  width = $(el.node()).width() //- margin.left - margin.right;
	var height = $(el.node()).height() //- margin.top - margin.bottom;

	var chart = d3.scatter()
		.height(height)
		.width(width)
		.ylabel(unit)
		.categoryMethod('delta_notation')
		.hoverMessage(function(d,el){
      var text = '<legend><h5>'+d.object.name+'</h5></legend>'
			text += 'Delta Notation: '+d.object.delta_notation+'<br/>'
			if(d.values.length ==1){
				text += 'Value: '+d.values[0]+'<br/><br/>'
			}else{
				text += 'Max: '+d3.max(d.values)+'<br/>'
				text += 'Min: '+d3.min(d.values)+'<br/><br/>'
				text += 'Click to view ' + d.values.length+' datapoints'
			}
      
      el.style('display','')
      .html(text)
		})
		.click(function(d){
			window.open('<%= results_path(genus: @species.genus, species: @species.species) %>'+'&measure_id='+d.object.id,'_blank')
		})
		
	el.datum(data).call(chart)
	
}


//https://bl.ocks.org/mbostock/4061502
$(document).ready(function(){

	// fatty acid graph
	var fa_data_0 = <%= "#{@fatty_acid_data.to_json}".html_safe %>
	var fa_el_0 = d3.select('#fa_plant_data_viz_0')
	drawBoxPlot(fa_data_0,fa_el_0,'GC-Area% or Weight%')
	
	
	// Oil Content parameter first
	
	<% if oil = @parameter_data["Oil content - weight-%"] %>
		<% @parameter_data.delete("Oil content - weight-%") %>
    var p_data_0 = <%= "#{oil.to_json}".html_safe %>
		var chart = c3.generate({
			bindto: '#p_plant_data_viz_0',
			data: {
        json: p_data_0,
				type: 'bar',
        keys: {value: ['value']},
        names: {value: "Oil content - weight-%"},
        onclick: function (d, element) { 
          window.open('<%= results_path %>'+'/'+p_data_0[d.index].id,'_blank')
        }
			}
		})
	<% end %>
	
	
	<% @parameter_data.each_with_index do |(key, subdata),index| %>
		<% index +=1 if oil %>
		<%= "var p_data_#{index} = #{subdata.to_json}".html_safe %>
		var chart = c3.generate({
			bindto: '<%= "#p_plant_data_viz_#{index}" %>',
			data: {
				json: p_data_<%= index %>,
        type: 'bar',
        keys: {value: ['value']},
				names: {value: '<%= key %>'},
        onclick: function (d, element) { 
          window.open('<%= results_path %>'+'/'+p_data_<%= index %>[d.index].id,'_blank')
        }
			}
		})
	<% end %>
	
});
</script>