config/routes.rb
Rails.application.routes.draw do
  scope '/plantfadb' do
    resources :dbxrefs
    resources :fatty_acids
    resources :results do
      get 'plant_yield', on: :collection
    end
    resources :measures do
      get :autocomplete_measure_name, :on => :collection
    end
    resources :plants do
      get :autocomplete_plant_name, :on => :collection
    end
    resources :pubs do
      collection do
        post 'condense_doi'
        post 'condense_wos'
      end
    end
    resources :plants_pubs
    resources :drafts
    devise_for :users
    resources :users
    resources :pages
    resources :tree, only: :index do
      get 'data', on: :collection
    end
    resources :datasets
    resources :tree_nodes do
      get :manage, on: :collection
      collection do
        post :sort
      end
    end

    root 'home#index'
    get 'stats' => 'stats#index'
    get 'history' => 'history#index'
    get 'species' => 'species#index', as: 'species'
    get ':genus/:species' => 'species#show', as: 'species_page'
    
    get 'bulk_uploads' => 'bulk_uploads#index'
    post 'check_file' => 'bulk_uploads#check_file'
    post 'process_file' => 'bulk_uploads#process_file'
    

  end
end

app/models/result.rb
# == Schema Information
#
# Table name: results
#
#  id             :integer          not null, primary key
#  value          :decimal(8, 2)
#  unit           :string
#  measure_id     :integer
#  publication_id :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  pub_id         :integer
#  plant_id       :integer
#  old_mol_val    :decimal(8, 2)
#  draft_id       :integer
#  published_at   :datetime
#  trashed_at     :datetime
#  plants_pub_id  :integer
#  dataset_id     :integer
#
# Indexes
#
#  index_results_on_measure_id      (measure_id)
#  index_results_on_publication_id  (publication_id)
#
# Foreign Keys
#
#  fk_rails_...  (measure_id => measures.id)
#  fk_rails_...  (publication_id => publications.id)
#

class Result < ActiveRecord::Base
  belongs_to :measure
  belongs_to :publication
  belongs_to :dataset
  delegate :plants_pub, to: :dataset
  delegate :plant, to: :plants_pub
  delegate :pub, to: :plants_pub
  
  has_paper_trail
  has_drafts
  after_save_draft :touch_dataset
  after_draft_destruction :touch_dataset
  
  scope :viewable, -> { where(unit: ['GLC-Area-%','weight-%']) }
  validates :value, :measure_id, :unit, presence: true
  
  def display_name
    "#{measure.display_name}"
  end
  
  def sofa_tab_id
    publication.try(:sofa_tab_id)
  end
  
  # Results are published/reverted by parent dataset
  # Always update parent when this item is drafted unless its already a draft
  def touch_dataset
    dataset.attributes = {updated_at: Time.now}
    dataset.save_draft
  end
  
  # Avoid circular dependency
  def draft_publication_dependencies
    []
  end
  
  def draft_reversion_dependencies
    []
  end
  
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  load_and_authorize_resource

  # GET /results
  def index
    @measure_types = Measure.select(:type).distinct.map(&:type)
    @results = @results.order(sort_column + ' ' + sort_direction).order("results.id ASC")
                       .includes(:measure, :publication, dataset: [plants_pub: [:plant, :pub]])
                       .references(:measure, :publication, dataset: [plants_pub: [:plant, :pub]])
                       .published.viewable
                       
    if params[:query]
      q = params[:query].upcase
      @results = @results.where('
        upper(value) LIKE ?
        OR upper(measures.type) LIKE ?
        OR upper(measures.delta_notation) LIKE ?
        OR upper(unit) LIKE ?
        OR upper(pubs.wos_year) LIKE ?
        OR upper(pubs.wos_authors) LIKE ?
        OR upper(pubs.wos_journal) LIKE ?
        OR upper(pubs.wos_volume) LIKE ?
        OR upper(pubs.wos_pages) LIKE ?
        OR upper(pubs.wos_title) LIKE ?
        OR upper(pubs.wos_uid) LIKE ?
        OR upper(pubs.remarks) LIKE ?
        OR upper(publications.sofa_tab_id) LIKE ?
        OR upper(plants.common_name) LIKE ?
        OR upper(plants.variety) LIKE ?
        OR upper(plants.species) LIKE ?
        OR upper(plants.genus) LIKE ?
        OR upper(plants.family) LIKE ?
        OR upper(plants.order_name) LIKE ?
        OR upper(plants.sofa_name) LIKE ?',
        "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%","%#{q}%","%#{q}%", "%#{q}%","%#{q}%","%#{q}%","%#{q}%","%#{q}%","%#{q}%","%#{q}%","%#{q}%"
      )
    end
    unless params[:taxon].blank?
      taxon = params[:taxon].split(',').map(&:strip)
      @results = apply_taxon(@results,taxon)
    end
    if params[:measure_type]
      @results = @results.where("measures.type =?",params[:measure_type])
    end
    if params[:plant_id] && @plant = Plant.find_by(id: params[:plant_id])
      @results = @results.where(plants_pubs: {plant_id: params[:plant_id]})
    end
    if params[:pub_id] && @pub = Pub.find_by(id: params[:pub_id])
      @results = @results.where(plants_pubs: {pub_id: params[:pub_id]})
    end
    if params[:measure_id] && @measure = Measure.find_by(id: params[:measure_id])
      @results = @results.where(measure_id: params[:measure_id])
    end
    if params[:category]
      @results = @results.where("measures.category = ?", params[:category])
    end
    if params[:genus].present? && params[:species].present?
      @species = Species.new(params[:genus],params[:species])
      @results = @results.where(plants: {id: @species.plants})
    end
    
    respond_to do |format|
      # Base html query
      format.html{ @results = @results.page params[:page]}
      # CSV download
      format.csv{
        render_csv do |out|
          out << CSV.generate_line(["Measure", "Notation", "Publication", "Value", "Unit"])
          @results.find_each(batch_size: 500) do |item|
            out << CSV.generate_line([
              item.measure.type,
              item.measure.name,
              item.measure.delta_notation,
              item.pub.display_name,
              item.value,
              item.unit
            ])
          end
        end
      }
    end
  end

  def plant_yield
    @results = Result.includes(:measure, dataset: [plants_pub: [:plant, :pub]]).published
    .references(:measure, dataset: [plants_pub: [:plant, :pub]])
    .where(measures: {type: ['FattyAcid']})
    .where(unit:  ['GLC-Area-%','weight-%'])
    if params[:measure_id] && @measure = Measure.find_by(id: params[:measure_id])
      @results = @results.where(measure_id: params[:measure_id])
    end
    unless params[:category].blank?
      @results = @results.where("measures.category = ?", params[:category])
    end
    unless params[:taxon].blank?
      taxon = params[:taxon].split(',').map(&:strip)
      @results = apply_taxon(@results,taxon,{group: true})
    end
    count = @results.count
    max = @results.maximum(:value)#.to_f.try(:round,4)
    avg = @results.average(:value)#.to_f.try(:round,4)
      
    data = []
    count.each do |name,cnt|
      data << {
        id: name,
        name: name.is_a?(Array) ? name.join(' ') : name,
        common_name: name,
        max: max[name].to_f.try(:round,4),
        avg: avg[name].to_f.try(:round,4),
        count: cnt,
        taxon: taxon+name.split(',')
      }
    end
    data = data.sort{|a,b|a[:name]<=>b[:name]}
    p = get_plants(taxon).count
    p_data = []
    p.each do |name,p_cnt|
      next unless name
      unless count[name]
        p_data << {
          id: name,
          name: name.is_a?(Array) ? name.join(' ') : name,
          common_name: name,
          max: nil, avg: nil, count: nil, taxon: taxon+name.split(',')
        }
      end
    end
    p_data.sort!{|a,b|a[:name]<=>b[:name]}
    data.concat(p_data)
    render json: data
  end

  # POST /results
  def create
    @dataset = @result.dataset
    @form_id = params[:form_id]
    if @result.save_draft
      @original_result = (@result.draft? ? @result.draft.reify : @result)
    else
      @original_result = @result
    end
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /results/1
  def update
    @result.attributes = resource_params
    if @result.save_draft
      redirect_to edit_dataset_path(@result.dataset)
    else
      redirect_to edit_dataset_path(@result.dataset), notice: 'Datapoint could not be updated.'
    end
  end

  # DELETE /results/1
  def destroy
    @dataset = @result.dataset
    @original_result = (@result.draft? ? @result.draft.reify : @result)
    @form_id = params[:form_id]
    if @result.draft? && @result.draft.create?
      @result.destroy
    else
      @result.draft_destruction
    end
    respond_to do |format|
     format.js{}
     format.html{redirect_to edit_dataset_path(@result.dataset), notice: 'Datapoint removed.'}
    end
    
  end

  private
    def apply_taxon(results, taxon,opts={})
      return results if taxon.blank? || taxon.empty?
      case taxon.length
      # clade / order
      when 1
        # Check for higher clade tree member first
        if t = TreeNode.find_by(name: taxon[0])
          names = t.subtree.map(&:name)
          results = results.where(plants: {order_name: names})
        else
          # lookup order
          results = results.where(plants: {order_name: taxon[0]})
        end
        results = results.group(:family) if opts[:group]
      # order,family
      when 2
        results = results.where(plants: {
          order_name: taxon[0],
          family: taxon[1]
        })
        results = results.group(:genus,:species) if opts[:group]
      # order,family,genus
      when 3
        results = results.where(plants: {
          order_name: taxon[0],
          family: taxon[1],
          genus: taxon[2]
        })
      else
        results = results.where(plants: {
          order_name: taxon[0],
          family: taxon[1],
          genus: taxon[2],
          species: taxon[3]
        })
      end
      return results
    end
    
    def get_plants(taxon)
      return [] if taxon.blank? || taxon.empty?
      case taxon.length
      when 1
        # Check for higher clade tree member first
        if t = TreeNode.find_by(name: taxon[0])
          names = t.subtree.map(&:name)
          plants = Plant.where(order_name: names).published
        else
          # lookup order
          plants = Plant.where(order_name: taxon[0]).published
        end
        plants = plants.group(:family)
      when 2
        plants = Plant.where(
          order_name: taxon[0],
          family: taxon[1]
        ).published
        plants = plants.group(:genus,:species)
      when 3
        plants = Plant.where(
          order_name: taxon[0],
          family: taxon[1],
          genus: taxon[2]
        ).published
        plants = plants.group(:species)
      else
        plants= []
      end
    end
    
    # Only allow a trusted parameter "white list" through.
    def resource_params
      params.require(:result).permit(:value, :unit, :measure_id, :dataset_id)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :measure_id %><br>
    <%= f.text_field :measure_id %>
  </div>
  <div class="field">
    <%= f.label :pub_id %><br>
    <%= f.text_field :pub_id %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/results/create.js.erb
$('#<%= @form_id %>').replaceWith("<%= j render partial: 'datasets/result_form', locals: {result: @result, original_result: @original_result, dataset_id: @dataset.id, form_id: @form_id } %>");  

app/views/results/destroy.js.erb
$('#<%= @form_id %>').replaceWith("<%= j render partial: 'datasets/result_form', locals: {result: @result, original_result: @original_result, dataset_id: @dataset.id, form_id: @form_id } %>");

app/views/results/edit.html.erb
<% content_for :top_bar do %>
  <h1 class="pagetitle">Editing Result</h1>
<% end %>

<% content_for :item_bar do %>
  <%= link_to 'Back', results_path, class: 'btn btn-primary' %>
<% end %>

<%= render 'form' %>

app/views/results/index.html.erb
<% content_for :top_bar do %>
	<h1 class="pagetitle">Data Points</h1>
	<% if @plant %>
		<p>
			Filtering on plant: <b><%= link_to @plant.display_name, @plant %></b>
		</p>
	<% end %>

	<% if @pub%>
		<p>
			Filtering on publication: <b><%= link_to @pub.display_name, @pub %></b>
		</p>
	<% end %>
	<% if @measure%>
		<p>
			Filtering on <%= @measure.class %>: <b><%= link_to @measure.name||@measure.delta_notation, @measure %></b>
		</p>
	<% end %>
	<% if params[:category] %>
		<p>
			Filtering on category: <b><%= link_to params[:category],fatty_acids_path(category: params[:category]) %></b>
		</p>
	<% end %>
	<% if params[:taxon] %>
		<p>
			Filtering on taxon: <b><%= params[:taxon] %></b>
		</p>
	<% end %>
	<% if @species %>
		<p>
			Filtering on: <b><%= link_to @species.name, species_page_path(genus: @species.genus, species: @species.species) %></b>
		</p>
	<% end %>
  
<% end %>

<% content_for :item_bar do %>
    <%= link_to 'Download', params.merge(format: 'csv'), class: 'btn btn-primary'%>
<% end %>


<%= render layout: 'shared/page_and_search', locals: {items: @results} do %>
<br style='clear:both'/>
	<div class='form-inline pull-right'>
		<br/>
		<label for="measure_type">Measure:</label>
		<%= select_tag :measure_type, options_for_select(@measure_types, params[:measure_type]),
			{	include_blank: true,
				class: 'form-control',
				onchange: 'this.form.submit()'} %>
	</div>
<% end %>

<div class='panel table-responsive'>
	
	<div class="panel-heading clearfix">
		<div class='pull-right'><%= page_entries_info @results %><br/>
		</div>
	</div>
	
  <table class='table table-striped'>
    <thead>
      <tr>
				<% unless @measure %>
	        <th><%= sortable "measures.type", "Measure" %></th>
					<th><%= sortable "measures.name", "Name" %></th>
	        <th><%= sortable "measures.delta_notation", "Notation" %></th>
				<% end %>
				<% unless @pub %>
        	<th><%= sortable "pubs.wos_authors", "Publication" %></th>
				<% end %>
				<% unless @plant || @species%>
					<th><%= sortable "plants.genus", "Plant" %></th>
				<% end %>
				<th></th>
        <th><%= sortable "value" %></th>
        <th><%= sortable "unit" %></th>
      </tr>
    </thead>

    <tbody>
      <% @results.each do |result| %>
        <tr>
					<% unless @measure %>
          	<td><%= result.measure.try :type %></td>
						<td><%= result.measure.try :name %></td>
          	<td><%= link_to_if result.measure.is_a?(FattyAcid), result.measure.try(:delta_notation), result.measure  %></td>
					<% end %>
					<% unless @pub %>
            <td><%= link_to result.pub.display_name, datasets_path(plant_id: result.plant.try(:id), pub_id: result.pub.id) if result.pub %></td> 
					<% end %>
					<% unless @plant || @species %>
            <td><%= link_to result.plant.display_name, datasets_path(plant_id: result.plant.id, pub_id: result.pub.try(:id)) if result.plant %></td> 
					<% end %>
					<td>
            <% if (xref = result.dataset.dbxref_value) && result.dataset.dbxref %>
              <%= result.dataset.dbxref.generate_link(xref) %>
            <% end %>
          </td>
          <td><%= result.value.to_f.round(2) %></td>
          <td><%= '*' if result.old_mol_val %> <%= result.unit %></td>         
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% unless @results.map(&:old_mol_val).compact.empty? %>
	<div class='pull-right'>
		<i>* Converted from mol %</i>
	</div>
<% end %>

app/views/results/new.html.erb
<% content_for :top_bar do %>
  <h1 class="pagetitle">New Result</h1>
<% end %>

<% content_for :item_bar do %>
  <%= link_to 'Back', results_path, class: 'btn btn-primary' %>
<% end %>

<%= render 'form' %>

app/views/results/show.html.erb
<% content_for :top_bar do %>
	<h1 class="pagetitle"><%= @result.measure.display_name %>: <%= @result.value %> <span class='small'><%= @result.unit %></span></h1>
<% end %>

<% content_for :top_bar do -%>
    <%= render :partial => "plants_pubs/header", locals: {pub: @result.pub, plant: @result.plant} %>
<% end -%>

<% content_for :item_bar do %>
	<%= link_to 'Back', results_path, class: 'btn btn-primary' %>
  <%= link_to 'Edit', edit_result_path(@result), class: 'btn btn-primary' %>
<% end %>

<%= link_to "View Dataset", plants_pub_path(@result.plants_pub), class: 'btn btn-primary' %>