config/routes.rb
Rails.application.routes.draw do
  scope '/plantfadb' do
    resources :dbxrefs
    resources :fatty_acids
    resources :results do
      get 'plant_yield', on: :collection
    end
    resources :measures do
      get :autocomplete_measure_name, :on => :collection
    end
    resources :plants do
      get :autocomplete_plant_name, :on => :collection
    end
    resources :pubs do
      collection do
        post 'condense_doi'
        post 'condense_wos'
      end
    end
    resources :plants_pubs
    resources :drafts
    devise_for :users
    resources :users
    resources :pages
    resources :tree, only: :index do
      get 'data', on: :collection
    end
    resources :datasets
    resources :tree_nodes do
      get :manage, on: :collection
      collection do
        post :sort
      end
    end

    root 'home#index'
    get 'stats' => 'stats#index'
    get 'history' => 'history#index'
    get 'species' => 'species#index', as: 'species'
    get ':genus/:species' => 'species#show', as: 'species_page'
    
    get 'bulk_uploads' => 'bulk_uploads#index'
    post 'check_file' => 'bulk_uploads#check_file'
    post 'process_file' => 'bulk_uploads#process_file'
    

  end
end

app/models/pub.rb
# == Schema Information
#
# Table name: pubs
#
#  id            :integer          not null, primary key
#  year          :string
#  authors       :string
#  journal       :string
#  volume        :string
#  page          :string
#  remarks       :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  wos_uid       :string
#  wos_journal   :string
#  wos_title     :string(500)
#  wos_volume    :string
#  wos_authors   :string
#  wos_pages     :string
#  wos_year      :string
#  doi           :string
#  original_pubs :text
#  abstract      :string(4000)
#  url           :string(1000)
#  draft_id      :integer
#  published_at  :datetime
#  trashed_at    :datetime
#  user_id       :integer
#  note          :string
#

class Pub < ActiveRecord::Base
  has_many :plants_pubs, dependent: :destroy
  has_many :datasets, through: :plants_pubs
  has_many :plants, through: :plants_pubs
  has_many :sofa_tabs, dependent: :destroy
  has_many :results, through: :plants_pubs
  serialize :original_pubs, Array
  validates :wos_authors, presence: true
  validates :wos_journal, presence: true
  validates :wos_title, presence: true
  include BulkData
  
  has_paper_trail
  has_drafts
  def display_name
    s = "#{wos_title} #{wos_authors} #{wos_journal} #{wos_year.blank? ? '' : "(#{wos_year})"}  #{wos_volume} #{wos_pages}"
    s = '-' if s.blank?
    s.html_safe
  end
  
  def self.bulk_columns
    {
      "authors" => :wos_authors,
      "year" => :wos_year,
      "title" => :wos_title,
      "journal" => :wos_journal,
      "volume" => :wos_volume,
      "pages" => :wos_pages,
      "doi" => :doi,
      "uid" => :wos_uid,
      "abstract" => :abstract,
      "url" => :url
    }
  end
  def bulk_valid?(pubs)
    return true
  end
  
  # Condense is currently disabled
  # These methods were previously used to allow merging multiple identical publications
  # based on the DOI or WOS_UID
  
  # def self.condense_wos
  #   hsh = {}
  #   total_begin_pubs = Pub.count
  #   # Grab all WOS into hash
  #   found = 0
  #   Pub.find_each do |pub|
  #     next if pub.wos_uid.blank? || pub.wos_uid.downcase=='none'
  #     hsh[pub.wos_uid]||=[]
  #     hsh[pub.wos_uid]<<pub
  #     found +=1
  #   end
  #   result = self.condense_hash(hsh)
  #   return result.merge({
  #     found: found,
  #     begin_count: total_begin_pubs,
  #     end_count: Pub.count
  #     })
  # end
  
  # def self.condense_doi
 #    hsh = {}
 #    total_begin_pubs = Pub.count
 #    # Grab all DOI into hash
 #    found = 0
 #    Pub.find_each do |pub|
 #      next if pub.doi.blank? || pub.doi.downcase=='none'
 #      hsh[pub.doi]||=[]
 #      hsh[pub.doi]<<pub
 #      found +=1
 #    end
 #    result = self.condense_hash(hsh)
 #    return result.merge({
 #      found: found,
 #      begin_count: total_begin_pubs,
 #      end_count: Pub.count
 #      })
 #  end
  
  # def self.condense_hash hsh
  #   dest = 0
  #   crt = 0
  #   skip = 0
  #   # Loop over full hash, condense non unique entries
  #   Pub.transaction do
  #     hsh.each do |key,pubs|
  #       # do nothing if unique
  #       if pubs.length == 1
  #         skip+=1
  #         next
  #       end
  #       # sort the array - latest == best
  #       pubs = pubs.sort_by {|p| p.id}.reverse
  #       # Collect items with original sofa data
  #       originals = (pubs.map(&:original_pubs).flatten + [pubs]).flatten.compact.reject{|p|
  #         p.year.nil? && p.authors.nil? && p.journal.nil? && p.volume.nil? && p.page.nil?
  #       }
  #       originals = nil if originals.empty?
  #       # build pub
  #       new_pub = Pub.new(
  #         wos_uid: pubs.reject{|p| p.wos_uid.nil?}.first.try(:wos_uid),
  #         wos_journal: pubs.reject{|p| p.wos_journal.nil?}.first.try(:wos_journal),
  #         wos_title: pubs.reject{|p| p.wos_title.nil?}.first.try(:wos_title),
  #         wos_volume: pubs.reject{|p| p.wos_volume.nil?}.first.try(:wos_volume),
  #         wos_authors: pubs.reject{|p| p.wos_authors.nil?}.first.try(:wos_authors),
  #         wos_pages: pubs.reject{|p| p.wos_pages.nil?}.first.try(:wos_pages),
  #         wos_year: pubs.reject{|p| p.wos_year.nil?}.first.try(:wos_year),
  #         doi: pubs.reject{|p| p.doi.nil?}.first.try(:doi),
  #         abstract: pubs.reject{|p| p.abstract.nil?}.first.try(:abstract),
  #         url: pubs.reject{|p| p.url.nil?}.first.try(:url),
  #         original_pubs: originals
  #       )
  #       crt += 1
  #       new_pub.save!
  #       new_pub.plants = pubs.map(&:plants).flatten.uniq
  #       pubs.each do |p|
  #         p.results.update_all(pub_id: new_pub.id)
  #         p.sofa_tabs.update_all(pub_id: new_pub.id)
  #         p.destroy
  #         dest+=1
  #       end
  #     end
  #   end
  #   return {
  #     unique: skip,
  #     created: crt,
  #     removed: dest
  #   }
  # end
end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController
  require "unicode_utils/upcase"
  load_and_authorize_resource
  # GET /publications
  def index

    if ActiveRecord::Base.connection.adapter_name.downcase =~ /.*sqlite.*/
      @pubs = @pubs.order(sort_column + ' ' + sort_direction + ", pubs.id ASC")
    else
      @pubs = @pubs.order(sort_column + ' ' + sort_direction + " nulls last, pubs.id ASC")
    end

    result_count = Result.viewable.published
                       .joins(:measure, dataset: [plants_pub: [:pub, :plant]])
                       .group("pubs.id")
                       .select("count(distinct(results.id)) result_count, pubs.id pub_id")

    if (params[:plant_id] && @plant=Plant.find_by(id: params[:plant_id].to_i))
      result_count = result_count.where(plants: {id: @plant.id})
      @pubs = @pubs.joins(plants_pubs: [:plant])
                  .where(plants_plants_pubs: {id: @plant.id})
    end

    if params[:genus].present? && params[:species].present?
      @species = Species.new(params[:genus],params[:species])
      plant_ids = @species.plants.select("plants.id")
      result_count = result_count.where(plants: {id: plant_ids})
    end

    @pubs = @pubs.joins("left outer join (#{result_count.to_sql}) res on res.pub_id = pubs.id")
                .published.select("pubs.*, res.result_count")

    if(params[:query].present?)
      q = UnicodeUtils.upcase(params[:query])
      @pubs = @pubs.where('
        upper(wos_year) LIKE :q
        OR upper(wos_authors) LIKE :q
        OR upper(wos_journal) LIKE :q
        OR upper(wos_volume) LIKE :q
        OR upper(wos_pages) LIKE :q
        OR upper(wos_uid) LIKE :q
        OR upper(wos_title) LIKE :q
        OR upper(abstract) LIKE :q
        OR upper(doi) LIKE :q
        OR upper(note) LIKE :q',
         {q: "%#{q}%"}
      )
    end

    unless params[:title_query].blank?
      q = UnicodeUtils.upcase(params[:title_query])
      @pubs = @pubs.where("upper(wos_title) like ?","%#{q}%")
    end

    unless params[:author_query].blank?
      q = UnicodeUtils.upcase(params[:author_query])
      @pubs = @pubs.where("upper(wos_authors) like ?","%#{q}%")
    end

    unless params[:abstract_query].blank?
      q = UnicodeUtils.upcase(params[:abstract_query])
      @pubs = @pubs.where("upper(abstract) like ?","%#{q}%")
    end

    unless params[:journal_query].blank?
      q = UnicodeUtils.upcase(params[:journal_query])
      @pubs = @pubs.where("upper(wos_journal) like ?","%#{q}%")
    end

    unless params[:year_query].blank?
      q = UnicodeUtils.upcase(params[:year_query])
      @pubs = @pubs.where("upper(wos_year) like ?","%#{q}%")
    end

    respond_to do |format|
      # Base html query
      format.html{ @pubs = @pubs.page params[:page]}
      # CSV download
      format.csv{
        render_csv do |out|
          out << CSV.generate_line([
                                       "ID","WOS_Authors","WOS_Year","WOS_Title","WOS_Journal","WOS_Volume","WOS_Pages",
                                       "DOI","WOS_UID","Abstract","URL", "NOTE",
                                       "SOFA Authors","SOFA Year","SOFA Journal","SOFA Volume","SOFA Page",
                                       "SOFA TABS"
                                   ])
          @pubs.find_each do |item|
            all_pubs = [item]+item.original_pubs
            out << CSV.generate_line([
                                         (can? :edit, item) ? "=HYPERLINK(\"#{root_url}js_redirect.html?page=#{edit_pub_path(item.id)}\",\"#{item.id}\")" : item.id,
                                         item.wos_authors,
                                         item.wos_year,
                                         item.wos_title,
                                         item.wos_journal,
                                         item.wos_volume,
                                         item.wos_pages,
                                         item.doi,
                                         item.wos_uid,
                                         item.abstract,
                                         item.url,
                                         item.note,
                                         all_pubs.map(&:authors).join("; "),
                                         all_pubs.map(&:year).join("; "),
                                         all_pubs.map(&:journal).join("; "),
                                         all_pubs.map(&:volume).join("; "),
                                         all_pubs.map(&:page).join("; ")
                                     ]+item.sofa_tabs.map{|tab|"=HYPERLINK(\"#{tab.sofa_url}\",\"#{tab.sofa_tab_id||'#'}\")"})
          end
        end
      }
    end
  end

  # GET /publications/1
  def show
    @plants_pubs= ActiveRecord::Base.connection.execute("SELECT * from genus_species(#{params[:id]});")
  end

  def new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  def create
    @pub.user_id = current_user.try(:id)
    if @pub.save_draft
      redirect_to @pub, notice: 'A draft of the new Publication was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /publications/1
  def update
    @pub.attributes = resource_params
    if @pub.save_draft
      redirect_to @pub, notice: 'A draft of the Publication update was saved.'
    else
      render :edit
    end
  end

  # DELETE /publications/1
  def destroy
    if @pub.plants_pubs.empty?
      @pub.draft_destruction
      redirect_to pubs_url, notice: 'Publication marked for destruction.'
    else
      redirect_to pubs_url, notice: 'Publication still has data. You must move or delete all publication tables first.'
    end
  end

  # def condense_doi
  #   result = Pub.condense_doi
  #   text = "Condense Complete:<br/><br/>
  #       Beginning Pub Count: #{result[:begin_count]}<br/>
  #       --<br/>
  #       Pub with DOI: #{result[:found]}<br/>
  #       Pub with unique DOI: #{result[:unique]}<br/>
  #       --<br/>
  #       Condensed: #{result[:removed]} <br/>
  #       New: #{result[:created]}<br/>
  #       --<br/>
  #       Ending Pub Count: #{result[:end_count]}
  #     "
  #   Rails.logger.info { text }
  #   redirect_to pubs_path, notice: text
  # end
  #
  # def condense_wos
  #   result = Pub.condense_wos
  #   text = "Condense Complete:<br/><br/>
  #       Beginning Pub Count: #{result[:begin_count]}<br/>
  #       --<br/>
  #       Pub with UID: #{result[:found]}<br/>
  #       Pub with unique UID: #{result[:unique]}<br/>
  #       --<br/>
  #       Condensed: #{result[:removed]} <br/>
  #       New: #{result[:created]}<br/>
  #       --<br/>
  #       Ending Pub Count: #{result[:end_count]}
  #     "
  #   Rails.logger.info { text }
  #   redirect_to pubs_path, notice: text
  # end

  private
  # Only allow a trusted parameter "white list" through.
  def resource_params
    params.require(:pub).permit(:doi,:wos_uid,:wos_title,:wos_year,:wos_authors,:wos_journal,:wos_volume,:wos_pages,
                                :year, :authors, :journal, :volume, :page, :url, :abstract, :note)
  end

  def sort_column
    col = ['wos_authors','wos_year', 'wos_title', 'wos_journal', 'wos_volume','doi','wos_uid', 'result_count'].find{|c| c==params[:sort]}
    col || "pubs.wos_authors, pubs.wos_year"
  end
end

app/views/pubs/edit.html.erb
<% content_for :top_bar do %>
  <h1 class="pagetitle">Editing Publication</h1>
<% end %>

<% content_for :item_bar do %>
  <%= link_to 'Cancel', @pub, class: 'btn btn-primary' %>
  <%= link_to 'Delete', @pub, class: 'btn btn-warning', method: :delete, data: {confirm: 'This item will be marked for deletion. You can apply this change by publishing it under the Data tab. Continue?'} if can? :delete, @pub %>
<% end %>

<%= render 'form' %>

app/views/pubs/index.html.erb
<% content_for :title do -%>
 PlantFAdb: Literature
<% end -%>

<% content_for :description do -%>
  Information on more than 3000 publications on plant fatty acids with links to species analyzed, analytical data, and full text of publications
<% end -%>

<% content_for :top_bar do %>
	<h1 class="pagetitle">Literature Listing</h1>
  <p>
    Information on more than 3000 publications on plant fatty acids with links to species analyzed, analytical data, and full text of publications
  </p>
	<% if @plant %>
		<p>
			Filtering on plant: <b><%= link_to @plant.display_name, @plant %></b>
		</p>
	<% end %>
	<% unless params[:title_query].blank? %>
		<p>Filtering on Title: <b><%= params[:title_query] %></b></p>
	<% end %>
	<% unless params[:author_query].blank? %>
		<p>Filtering on Author: <b><%= params[:author_query] %></b></p>
	<% end %>
	<% unless params[:abstract_query].blank? %>
		<p>Filtering on Abstract: <b><%= params[:abstract_query] %></b></p>
	<% end %>
	<% unless params[:journal_query].blank? %>
		<p>Filtering on Journal: <b><%= params[:journal_query] %></b></p>
	<% end %>
	<% unless params[:year_query].blank? %>
		<p>Filtering on Year: <b><%= params[:year_query] %></b></p>
	<% end %>
	<% if @species %>
		<p>
			Filtering on: <b><%= link_to @species.name, species_page_path(genus: @species.genus, species: @species.species) %></b>
		</p>
	<% end %>
<% end %>

<% content_for :item_bar do %>
		<% if current_user && current_user.is_admin? %>
			<%#= link_to "Condense Using WOS UID", condense_wos_pubs_path, class: 'btn btn-primary',
			method: :post,
			data: {confirm: "This will take some time to run. ALL pubs with the same UID will be condensed into a single new publication. Pubs with a blank UID or 'none' will be skipped"} %>
			<%#= link_to "Condense Using DOI", condense_doi_pubs_path, class: 'btn btn-primary',
			method: :post,
			data: {confirm: "This will take some time to run. ALL pubs with the same DOI will be condensed into a single new publication. Pubs with a blank DOI or a doi of 'none' will be skipped"} %>
		<% end %>
    <%= link_to 'Download', params.merge(format: 'csv'), class: 'btn btn-primary'%>
<% end %>

<div class='row'>
	<div class='col-xs-12 col-sm-7 col-md-8 pull-left'>
		<ul class="pagination">
			<%= paginate @pubs %>
		</ul>
	</div>
	<div class='col-xs-12 col-sm-5 col-md-4 search'>
    <%= form_tag nil, method: :get do %>
		<% params.except(:commit,:action,:controller,:utf8,:query,:page).each do |parameter, val| %>
			<%= hidden_field_tag parameter, val %>
		<% end %>
      <div class='form-inline pull-left-sm pull-right-md'>
				<div class='form-group'>
          <a href='<%= Page.path('help') %>' class='glyphicon glyphicon-question-sign' data-toggle='tooltip' data-html='true' title="
            Simple search includes Author, title, journal, abstract and year. <br/><br/>
            
            Diacritical marks such as German umlaut(ä, ö and ü) are not recorded consistently in the literature and should be searched with more than one spelling. <br/> e.g. <br/>
            Ölsäure -> Oelsaeure or Olsaure <br/>
            Aitzetmüller -> Aitzetmueller or Aitzetmuller<br/><br/>
            
            Click for more details.
          "></a>
			    <label for="query">Search:</label>
					<%= text_field_tag :query, params[:query], class: 'form-control' %>
					<%= submit_tag "Go", class: "btn btn-info"%>
				</div>
					<br/>
					<div class='pull-left-sm pull-right-md'>
						<%= link_to "Advanced Query", '#', onclick: "$('#advanced_search').toggle()"%>
					</div>
			</div>
    <% end %>
	</div>
</div>

<div id='advanced_search' class='well form-horizontal' style='display:none;width:100%'>
	<%= form_tag nil, method: :get do %>
		
		<div class='form-group'>
			<%= label_tag :title_query, "Title", class: 'col-sm-2' %>
			<div class='col-sm-8'>
				<%= text_field_tag :title_query, params[:title_query], class: 'form-control' %>
			</div>
		</div>
    
		<div class='form-group'>
			<%= label_tag :author_query, "Author", class: 'col-sm-2' %>
			<div class='col-sm-8'>
				<%= text_field_tag :author_query, params[:author_query], class: 'form-control' %>
			</div>
		</div>
		
		<div class='form-group'>
			<%= label_tag :abstract_query, "Abstract", class: 'col-sm-2' %>
			<div class='col-sm-8'>
				<%= text_field_tag :abstract_query, params[:abstract_query], class: 'form-control' %>
			</div>
		</div>
    
		<div class='form-group'>
			<%= label_tag :journal_query, "Journal", class: 'col-sm-2' %>
			<div class='col-sm-8'>
				<%= text_field_tag :journal_query, params[:journal_query], class: 'form-control' %>
			</div>
		</div>
    
		<div class='form-group'>
			<%= label_tag :year_query, "Year", class: 'col-sm-2' %>
			<div class='col-sm-8'>
				<%= text_field_tag :year_query, params[:year_query], class: 'form-control' %>
			</div>
		</div>
		
		<%= submit_tag "Search", class: "btn btn-info"%>
		<%= link_to "Clear Query", pubs_path, class: 'btn btn-warning pull-right' %>
	<% end %>
</div>

<div class='panel table-responsive'>
	
	<div class="panel-heading clearfix">
		<div class='pull-right'><%= page_entries_info @pubs %></div>
	</div>
	
  <table class='table table-striped'>
    <thead>
      <tr>
				<th style='width:20%'><%= sortable "wos_authors", "Authors" %></th>
				<th><%= sortable "wos_year", "Year"%></th>
				<th style='width: 20px'></th>
				<th style='width:30%'><%= sortable "wos_title", "Title" %></th>
				<th><%= sortable "wos_journal", "Journal" %></th>
        <th><%= sortable "wos_volume", "Volume" %></th>
				<th>Pages</th>
				<th><%= sortable "doi", "DOI" %></th>
				<th><%= sortable "wos_uid", "UID" %></th>
        <th><%= sortable "result_count", "Data points" %></th>
      </tr>
    </thead>

    <tbody>
      <% @pubs.each do |publication| %>
        <tr>
					<td><%= link_to publication.wos_authors||"Unknown", publication %></td>
					<td><%= publication.wos_year %></td>
					<td class='pub-tooltip'>
						<% if publication.abstract %>
							<a tabindex="0" class="glyphicon glyphicon-text-color" role="button" data-toggle="popover" data-trigger="focus" title="Abstract" data-content="<%= publication.abstract %>"></a>
						<% end %>
					</td>
					<td><%= publication.wos_title %></td>
					<td><%= publication.wos_journal %></td>
					<td><%= publication.wos_volume %></td>
					<td><%= publication.wos_pages %></td>
					<td><%= link_to publication.doi, "https://doi.org/#{publication.doi}", target: '_blank' if publication.doi && publication.doi.downcase != 'none' %></td>
					<td><%= publication.wos_uid %></td>
          <td><%= link_to publication.result_count||0, datasets_path(pub_id: publication.id, plant_id: @plant) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class='row'>
	<div class='col-xs-12 col-sm-7 col-md-8'>
		<ul class="pagination pull-left">
			<%= paginate @pubs %>
		</ul>
	</div>
</div>

app/views/pubs/new.html.erb
<% content_for :top_bar do %>
  <h1 class="pagetitle">New Publication</h1>
<% end %>

<% content_for :item_bar do %>
  <%= link_to 'Back', drafts_path, class: 'btn btn-primary' %>
<% end %>

<%= render 'form' %>

app/views/pubs/show.html.erb
<% content_for :title do -%>
  PlantFAdb: <%= "#{@pub.wos_title}." if @pub.wos_title && @pub.wos_title.downcase != 'none' %> <%= @pub.display_name %>
<% end -%>

<% content_for :description do -%>
  Information on over 1500 publications on plant fatty acids with links to species analyzed, analytical data, and full text of publications. <%= "#{@pub.wos_title}." if @pub.wos_title && @pub.wos_title.downcase != 'none' %> <%= @pub.display_name %>
<% end -%>

<% content_for :top_bar do %>
  <% unless @pub.published? %>
    <p class='bg-warning'>This is an unpublished draft. <%= link_to 'Click here to view all draft data', drafts_path %></p>
  <% end %>
  <h1 class="pagetitle"><%= @pub.wos_title %></h1>
<% end %>

<% content_for :item_bar do %>
  <%= link_to 'Back', pubs_path, class: 'btn btn-primary' %>
  <% if can? :edit, @pub %>
    <%= link_to 'Edit', edit_pub_path(@pub), class: 'btn btn-primary' %>
    <%= link_to "Add Plant", new_plants_pub_path(pub_id: @pub.id), class: 'btn btn-primary' %>
  <% end %>
<% end %>

<% if @pub.abstract %>
  <div class='row'>
    <div class='well col-md-12'>
      <legend>Abstract</legend>
      <%= @pub.abstract %>
    </div>
  </div>
<% end %>

<div class='row'>
  <div class='well col-sm-12 col-md-5' style='overflow:auto'>
    <legend>Citation</legend>
    <p>
      <strong>Authors:</strong>
      <%= @pub.wos_authors %>
    </p>

    <p>
      <strong>Journal:</strong>
      <%= @pub.wos_journal %>
    </p>

    <p>
      <strong>Year:</strong>
      <%= @pub.wos_year %>
    </p>

    <p>
      <strong>Volume:</strong>
      <%= @pub.wos_volume %>
    </p>

    <p>
      <strong>Page:</strong>
      <%= @pub.wos_pages %>
    </p>

    <p>
      <strong>UID:</strong>
      <%= @pub.wos_uid %>
    </p>

    <% if @pub.url %>
      <p>
        <strong>URL:</strong>
        <%= link_to @pub.url, @pub.url, target: '_blank'%>
      </p>
    <% end %>

    <% unless @pub.doi.blank? || @pub.doi.downcase == 'none' %>
      <p>
        <strong>DOI:</strong>
        <%= link_to @pub.doi, "https://doi.org/#{@pub.doi}", target: '_blank'%>
      </p>
    <% end %>
  </div>

  <div class='col-sm-12 col-md-7 well pull-right'>
    <legend>Plants</legend>
    <% if @pub.datasets.count > 1 %>
		<span> 
			<%= link_to "View All #{@pub.datasets.count} Datasets", datasets_path(pub_id: @pub.id) %>
		</span>
    <% end %>
    <table class="table">
      <thead>
      <th>Genus</th>
      <th>Species</th>
      <th>Data Points</th>
      <th></th>
      <th></th>
      </thead>
      <tbody>
      <% @plants_pubs.each do |pb| %>
        <tr>
          <td><%= link_to pb['genus']||"Unknown", datasets_path(plant_id: pb['plant_id'], pub_id: pb['pub_id']) %></td>
          <td><%= link_to pb['species']||"Unknown", datasets_path(plant_id: pb['plant_id'], pub_id: pb['pub_id']) %></td>
          <td>
            <%= pb['count'] %>
            <% unless pb['remarks'].blank? %>
              <a class='pull-right glyphicon glyphicon-info-sign' data-toggle='tooltip' data-html='true' title="
                <%= "#{pb['name']}:<br/> #{pb['remarks']}<br/>" if pb['remarks']  %>
               "></a>
            <% end %>
            <td>
              <% if can? :edit, pb %>
                <%= link_to 'Edit', edit_plants_pub_path(pb['id']), class: 'btn btn-warning btn-xs' %>
              <% end %>
            </td>
            </td>
            </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <% if @pub.sofa_tabs.present? %>
    <div class='col-sm-12 col-md-5 pull-left well'>
      <legend>SOFA Table(s)</legend>
      <% @pub.sofa_tabs.each do |tab| %>
        <div style='float:left;margin:0.25em'><%= link_to (tab.sofa_tab_id||'#'), tab.sofa_url, target: '_blank' %></div>
      <% end %>
    </div>
  <% end %>
</div>