config/routes.rb
Rails.application.routes.draw do
  scope '/plantfadb' do
    resources :dbxrefs
    resources :fatty_acids
    resources :results do
      get 'plant_yield', on: :collection
    end
    resources :measures do
      get :autocomplete_measure_name, :on => :collection
    end
    resources :plants do
      get :autocomplete_plant_name, :on => :collection
    end
    resources :pubs do
      collection do
        post 'condense_doi'
        post 'condense_wos'
      end
    end
    resources :plants_pubs
    resources :drafts
    devise_for :users
    resources :users
    resources :pages
    resources :tree, only: :index do
      get 'data', on: :collection
    end
    resources :datasets
    resources :tree_nodes do
      get :manage, on: :collection
      collection do
        post :sort
      end
    end

    root 'home#index'
    get 'stats' => 'stats#index'
    get 'history' => 'history#index'
    get 'species' => 'species#index', as: 'species'
    get ':genus/:species' => 'species#show', as: 'species_page'
    
    get 'bulk_uploads' => 'bulk_uploads#index'
    post 'check_file' => 'bulk_uploads#check_file'
    post 'process_file' => 'bulk_uploads#process_file'
    

  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  load_and_authorize_resource
  def index
    @drafts = @drafts.includes(:item)
                     .order('updated_at DESC')
                     .where(item_type: ["Pub","Plant","Measure","PlantsPub","Dataset"])
                     .page(params[:page])
  end

  def show
  end

  # Post draft ID here to publish it
  def update
    # Call `draft_publication_dependencies` to check if any other drafted records should be published along with this
    # `@draft`.
    #@dependencies = @draft.draft_publication_dependencies

    # If you would like to warn the user about dependent drafts that would need to be published along with this one, you
    # would implement an `app/views/drafts/update.html.erb` view template. In that view template, you could list the
    # `@dependencies` and show a button posting back to this action with a name of `commit_publication`. (The button's
    # being clicked indicates to your application that the user accepts that the dependencies should be published along
    # with the `@draft`, thus avoiding orphaned records).
    #if @dependencies.empty? || params[:commit_publication]
      @draft.publish!
      flash[:notice] = 'The draft was published successfully.'
      redirect_to drafts_path
      #else
      # Renders `app/views/drafts/update.html.erb`
      #end
  end

  # Post draft ID here to revert it
  def destroy
    # Call `draft_reversion_dependencies` to check if any other drafted records should be reverted along with this
    # `@draft`.
    #@dependencies = @draft.draft_reversion_dependencies ||[]

    # If you would like to warn the user about dependent drafts that would need to be reverted along with this one, you
    # would implement an `app/views/drafts/destroy.html.erb` view template. In that view template, you could list the
    # `@dependencies` and show a button posting back to this action with a name of `commit_reversion`. (The button's
    # being clicked indicates to your application that the user accepts that the dependencies should be reverted along
    # with the `@draft`, thus avoiding orphaned records).
    #if @dependencies.empty? || params[:commit_reversion]
      @draft.revert!
      flash[:notice] = 'The draft was reverted successfully.'
      redirect_to drafts_path
      #else
      # Renders `app/views/drafts/destroy.html.erb`
      #end
  end
end

app/views/drafts/_dependencies.html.erb
<div class='col-sm-12 col-md-5' id='on_<%= name %>'>
  <legend><small> On <%= name %>: <%= dependencies.count %></small></legend>
  <table class='table'>
    <thead>
      <th>Draft</th>
      <th>Name</th>
      <th>Type</th>
    </thead>
      <% dependencies.each do |draft| %>
        <% item = draft.reify %>
        <tr>
          <td>
            <%= link_to draft_path(draft) do %>
              <span class='<%= draft.event %>-tag'>
                <%= draft.create? ? "New" : draft.destroy? ? "Delete" : "Update"  %>
              </span>
            <% end %>
          </td>
          <td><%= item.display_name %></td>
          <td><%= draft.item.class.model_name.human  %></td>
        </tr>
      <% end %>
  </table>
</div>

app/views/drafts/index.html.erb
<% content_for :title do -%>
  PlantFAdb: Data Management
<% end -%>

<% content_for :top_bar do %>
  <h1 class="pagetitle">Data Management</h1>
<% end %>

<% content_for :item_bar do %>
  <%= link_to "Add Publication", new_pub_path, class: 'btn btn-primary' %>
  <%= link_to "Add Fatty Acid", new_fatty_acid_path, class: 'btn btn-primary' %>
  <%= link_to "Add Plant", new_plant_path, class: 'btn btn-primary' %>
<% end %>

Pending updates are shown below. They will be reviewed by the administrator before public release.

<div class='panel table-responsive'>
  <ul class="pagination">
    <%= paginate @drafts %>
  </ul>
  <div class='pull-right'><%= page_entries_info @drafts %></div>
  <table class='table table-striped table-centered'>
    <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Type</th>
      <% if current_user.is_admin? %>
        <th>User</th>
      <% end %>
      <th>Last Update</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @drafts.each do |draft| %>
      <% item = draft.reify %>
      <tr>
        <td>
            <span class='<%= draft.event %>-tag'>
              <%= draft.create? ? "New" : draft.destroy? ? "Delete" : "Update" %>
            </span>
        </td>
        <% if item.nil? %>
          <td></td>
          <td></td>
        <% else %>
          <td><%= item.display_name %></td>
          <td><%= item.class.model_name.human %></td>
        <% end %>
        <% if current_user.is_admin? %>
          <td><%= User.find_by(id: draft.whodunnit).try(:email) %></td>
        <% end %>
        <td><%= local_time_ago(draft.updated_at) %></td>
        <td style='text-align:right;white-space:nowrap'>
          <% if current_user.is_admin? %>
            <%= link_to 'Publish', draft_path(draft), method: :put, class: 'btn btn-success', style: 'margin-right:1em' %>
          <% end %>
          <!-- Special Pub link -->
          <%= link_to "Add Data", new_plants_pub_path(pub_id: draft.item.id), class: 'btn btn-default', style: 'margin-right:1em' if draft.item.kind_of?(Pub) %>
          <%= link_to 'Details', draft_path(draft), class: 'btn btn-info', style: 'margin-right:1em' %>
          <%= link_to 'Revert', draft_path(draft), method: :delete, class: 'btn btn-warning', style: 'margin-right:1em' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/drafts/show.html.erb
<% content_for :top_bar do %>
	<h1 class="pagetitle">Draft <%= @draft.id %></h1><br/>
  <span class='<%= @draft.event %>-tag'><%= @draft.create? ? "New" : @draft.destroy? ? "Delete" : "Update"  %></span><br/>
<% end %>

<% content_for :item_bar do %>
	<%= link_to 'Back', drafts_path, class: 'btn btn-primary' %>
<% end %>

<div class='container'>
<div class='pull-left'>
  <b>User</b>: <%= User.find_by(id: @draft.whodunnit).try(:email)  %>
</div>

<div class='col-md-6  pull-right'>
  <% if @draft.item_type=='Result'%>
    <div>
      This Result is managed by the parent dataset.<br/>
      Publish the dataset to publish this draft: <br/>
      <%= link_to "View dataset: #{@draft.item.dataset.display_name}", @draft.item.dataset.try(:draft) ? draft_path(@draft.item.dataset.draft) : @draft.item.dataset, class: 'btn btn-success' %>
      <%= link_to 'Revert', draft_path(@draft), method: :delete, class: 'btn btn-default' %>
    </div>
    
  <% else %>
    <%= link_to 'Publish', draft_path(@draft), method: :put, class: 'btn btn-success', style: 'margin-right:1em' %>
    <%= link_to 'Revert', draft_path(@draft), method: :delete, class: 'btn btn-default' %>
  <% end %>
</div>

</div>

<br/>

<div class='container'>
  <div class='well col-sm-12 col-md-5'>
    <legend>Item details</legend>
    <b>Type:</b> <%= @draft.item.class.model_name.human %><br/>
    <b>Name:</b> <%= @draft.item.display_name %><br/><br/>
    <%= link_to "Click here to view current item", @draft.item %>
  </div>

  <div class='col-md-1'></div>
  <% if @draft.update? %>
    <div class='well col-sm-12 col-md-6'>
      <legend>Changes</legend>
      <table class='table'>
        <thead>
          <th>Field</th>
          <th>Old</th>
          <th>New</th>
        </thead>
          <% @draft.changeset.each do |field, vals| %>
            <tr>
              <td><%= field %></td>
              <td><%= vals[0] %></td>
              <td><%= vals[1] %></td>
            </tr>
          <% end %>
      </table>
    </div>
  <% end %>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <div class='panel-heading'><h2 class="panel-title">Dependent Items</h2></div>
    <div class='panel-body'>
      <% unless (@draft.draft_publication_dependencies||[]).empty? %>
          <%= render :partial => "dependencies", locals: {dependencies: @draft.draft_publication_dependencies, name: 'Publish'} %>
      <% end %>
      <% unless (@draft.draft_reversion_dependencies||[]).empty? %>
          <%= render :partial => "dependencies", locals: {dependencies: @draft.draft_reversion_dependencies, name: 'Revert'} %>
      <% end %>
    </div>
  </div>
</div>

app/views/drafts/update.html.erb
update